title: Abbas Hussain - Game Developer
email: abbas23hussain@gmail.com
description: >-
  Portfolio of Muhammad Abbas Hussain, a game developer with experience in Unreal Engine, Unity, and VR/AR.
baseurl: ""
url: "https://abbas23hussain.github.io"
theme: minima
plugins:
  - jekyll-feed
